package com.ruimendes.chat.database

import androidx.room.RoomDatabaseConstructor

@Suppress("KotlinNoActualForExpect", "NO_ACTUAL_FOR_EXPECT") // This will be auto-generated by Room
expect object AppChatDatabaseConstructor: RoomDatabaseConstructor<AppChatDatabase> {
    override fun initialize(): AppChatDatabase
}